import { CHALLENGE, EMOJIS, GOAL, READERS } from './src/config.js';
import { createBook, now, uuid, validBook, visibleBooks } from './src/state.js';
import { commit, loadLocal, loadOutbox, saveLocal, synchronize } from './src/sync.js';

let state = loadLocal(), editingEmoji = EMOJIS[0], lastFocus;
const $ = selector => document.querySelector(selector);
const el = (tag, attrs = {}, children = []) => { const node = document.createElement(tag); for (const [key, value] of Object.entries(attrs)) key === 'class' ? node.className = value : key.startsWith('on') ? node.addEventListener(key.slice(2), value) : node.setAttribute(key, value); for (const child of [].concat(children)) node.append(child instanceof Node ? child : document.createTextNode(String(child))); return node; };
const fmt = number => Math.round(number).toLocaleString('da-DK');
const books = () => visibleBooks(state);
const total = () => books().reduce((sum, book) => sum + book.pages, 0);
const operation = book => ({ operationId: uuid(), type: 'upsert', createdAt: now(), book });
const announce = message => { $('#notice').textContent = message; setTimeout(() => { if ($('#notice').textContent === message) $('#notice').textContent = ''; }, 5000); };

function syncStatus({ pending, phase, lastSync }) {
  const text = phase === 'syncing' ? `Synkroniserer… ${pending ? `${pending} ændringer afventer` : ''}` : phase === 'offline' ? `Offline · ${pending} ændringer afventer synkronisering` : `Synkroniseret kl. ${lastSync.toLocaleTimeString('da-DK', { hour: '2-digit', minute: '2-digit' })}`;
  $('#sync').textContent = text; $('#sync').className = `sync ${phase}`;
}
async function sync() { state = await synchronize(state, syncStatus); render(); }
function save(op, message) { state = commit(state, op); syncStatus({ pending: loadOutbox().length, phase: navigator.onLine ? 'syncing' : 'offline' }); render(); announce(message); sync(); }

function button(label, onClick, className = '') { return el('button', { type: 'button', class: className, onClick }, label); }
function render() { renderHome(); renderStats(); renderAdmin(); $('#mute').textContent = state.muted ? '🔇' : '🔊'; $('#mute').setAttribute('aria-label', state.muted ? 'Slå lyd til' : 'Slå lyd fra'); }
function renderHome() {
  const root = $('#home'); root.replaceChildren(); const progress = Math.min(100, total() / GOAL * 100);
  root.append(el('section', { class: 'hero' }, [el('div', { class: 'total' }, fmt(total())), el('p', {}, `af ${fmt(GOAL)} sider · ${progress.toFixed(1)} %`), el('progress', { class: 'progress', value: progress, max: 100, 'aria-label': 'Familiens fremdrift i procent' }), prizeEditor()]));
  const people = el('div', { class: 'people' }); READERS.forEach(reader => { const own = books().filter(b => b.reader === reader.id); const pages = own.reduce((n, b) => n + b.pages, 0); const badge = button(own.length ? '🚀' : '🔒', () => announce(own.length ? `${reader.name} har læst ${own.length} bøger.` : `${reader.name}: Første-bog-badget er stadig låst.`), 'badge'); badge.setAttribute('aria-label', 'Forklar badge'); people.append(el('article', { class: 'card person' }, [el('h2', {}, reader.name), el('strong', {}, `${fmt(pages)} sider`), badge])); }); root.append(people);
  root.append(logControls(), bookLog(), button('+ Tilføj bog', () => openEditor(), 'fab'));
}
function prizeEditor() { const wrap = el('div', { class: 'prize-edit' }); const input = el('input', { value: state.prize, maxlength: 200, 'aria-label': 'Familiens præmie', placeholder: 'Vælg familiens præmie' }); input.addEventListener('change', () => save({ operationId: uuid(), type: 'settings', createdAt: now(), updatedAt: now(), prize: input.value.trim() }, 'Præmien er gemt.')); wrap.append(el('label', {}, ['Præmie ', input])); return wrap; }
function logControls() { const wrap = el('div', { class: 'filters' }); wrap.innerHTML = '<label>Søg <input id="search" type="search" placeholder="Titel eller forfatter"></label><label>Læser <select id="reader-filter"><option value="">Alle</option></select></label><label>Måned <input id="month-filter" type="month"></label><label>Reaktion <select id="emoji-filter"><option value="">Alle</option></select></label><label>Sortér <select id="sort"><option value="date">Dato</option><option value="pages">Sidetal</option><option value="title">Titel</option></select></label>';
  READERS.forEach(r => $('#reader-filter', wrap)?.append(new Option(r.name, r.id))); // fallback below for browsers
  const readerSelect = wrap.querySelector('#reader-filter'); READERS.forEach(r => readerSelect.append(new Option(r.name, r.id))); EMOJIS.forEach(e => wrap.querySelector('#emoji-filter').append(new Option(e, e))); wrap.addEventListener('input', renderLogOnly); return wrap; }
function filtered() { const get = id => document.querySelector(id)?.value || ''; const query = get('#search').toLocaleLowerCase('da'); let result = books().filter(b => (!query || `${b.title} ${b.author}`.toLocaleLowerCase('da').includes(query)) && (!get('#reader-filter') || b.reader === get('#reader-filter')) && (!get('#month-filter') || b.date.startsWith(get('#month-filter'))) && (!get('#emoji-filter') || b.emoji === get('#emoji-filter'))); const sort = get('#sort'); return result.sort(sort === 'title' ? (a,b) => a.title.localeCompare(b.title,'da') : sort === 'pages' ? (a,b) => b.pages-a.pages : (a,b) => b.date.localeCompare(a.date)); }
function bookLog() { const section = el('section', { class: 'card log-wrap', id: 'book-log' }, el('h2', {}, 'Logbog')); fillLog(section); return section; }
function renderLogOnly() { fillLog($('#book-log')); }
function fillLog(section) { const heading = section.querySelector('h2') || el('h2', {}, 'Logbog'); section.replaceChildren(heading); let month = ''; for (const book of filtered()) { const current = book.date.slice(0, 7); if (current !== month) { month = current; section.append(el('h3', { class: 'month-heading' }, new Date(`${month}-01T12:00:00`).toLocaleDateString('da-DK', { month: 'long', year: 'numeric' }))); } const reader = READERS.find(r => r.id === book.reader); section.append(el('article', { class: 'book' }, [button(book.emoji, () => openDetail(book), 'book-emoji'), el('div', { class: 'book-main' }, [el('strong', {}, book.title), el('span', {}, `${book.author ? `${book.author} · ` : ''}${reader.name} · ${book.date}`)]), el('b', {}, `+${fmt(book.pages)}`), button('Redigér', () => openEditor(book), 'secondary'), button('Slet', () => trash(book), 'danger')])); } if (!filtered().length) section.append(el('p', {}, 'Ingen bøger matcher filtrene.')); }

function openEditor(book) { lastFocus = document.activeElement; const form = $('#book-form'); form.reset(); form.elements.id.value = book?.id || ''; form.elements.title.value = book?.title || ''; form.elements.author.value = book?.author || ''; form.elements.pages.value = book?.pages || ''; form.elements.date.value = book?.date || new Date().toISOString().slice(0,10); form.elements.reader.value = book?.reader || ''; form.elements.comment.value = book?.comment || ''; editingEmoji = book?.emoji || EMOJIS[0]; $('#dialog-title').textContent = book ? 'Redigér bog' : 'Tilføj bog'; renderEmojis(); $('#book-dialog').showModal(); form.elements.title.focus(); }
function renderEmojis() { const root = $('#emojis'); root.replaceChildren(...EMOJIS.map(emoji => { const b = button(emoji, () => { editingEmoji = emoji; renderEmojis(); }, `reaction ${emoji === editingEmoji ? 'active' : ''}`); b.setAttribute('aria-label', `Vælg reaktionen ${emoji}`); b.setAttribute('aria-pressed', emoji === editingEmoji); return b; })); }
$('#book-form').addEventListener('submit', event => { if (event.submitter?.value !== 'save') return; event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; const old = state.books.find(b => b.id === form.elements.id.value); const fields = Object.fromEntries(new FormData(form)); fields.emoji = editingEmoji; const book = old ? { ...old, ...createBook(fields, old.createdAt, old.id), createdAt: old.createdAt, updatedAt: now() } : createBook(fields); save(operation(book), old ? 'Bogen er opdateret.' : 'Bogen er tilføjet.'); $('#book-dialog').close(); lastFocus?.focus(); });
function trash(book) { const deleted = { ...book, deletedAt: now(), updatedAt: now() }; save(operation(deleted), `“${book.title}” er flyttet til papirkurven.`); const undo = button('Fortryd sletning', () => restore(deleted), 'undo'); $('#notice').append(' ', undo); }
function restore(book) { save(operation({ ...book, deletedAt: null, updatedAt: now() }), `“${book.title}” er gendannet.`); }
function openDetail(book) { const r = READERS.find(x => x.id === book.reader); $('#detail-content').replaceChildren(el('h2', { id: 'detail-title' }, book.title), el('p', {}, `${book.emoji} ${book.author || 'Ukendt forfatter'}`), el('p', {}, `${fmt(book.pages)} sider · ${r.name} · ${book.date}`), el('p', {}, book.comment || 'Ingen kommentar')); $('#detail-dialog').showModal(); }

function renderStats() { const root = $('#stats'); root.replaceChildren(el('h2', {}, 'Statistik'), ...READERS.map(r => { const own = books().filter(b => b.reader === r.id); return el('article', { class: 'card fact' }, [el('strong', {}, r.name), el('span', {}, `${own.length} bøger · ${fmt(own.reduce((n,b)=>n+b.pages,0))} sider`)]); })); }
function renderAdmin() { const root = $('#admin'); root.replaceChildren(el('h2', {}, 'Data, backup og papirkurv'), el('p', {}, 'Alle ændringer gemmes som append-only operationer og daglige snapshots på serveren. Slettede bøger opbevares i mindst 30 dage.'), button('Eksportér JSON', exportJson, 'secondary'), button('Eksportér CSV', exportCsv, 'secondary')); const input = el('input', { type: 'file', accept: 'application/json' }); input.addEventListener('change', importJson); root.append(el('label', { class: 'import' }, ['Importér JSON (forhåndsvises først) ', input]), el('h3', {}, 'Papirkurv')); state.books.filter(b => b.deletedAt).forEach(book => root.append(el('div', { class: 'trash-row' }, [el('span', {}, `${book.title} · slettet ${book.deletedAt.slice(0,10)}`), button('Gendan', () => restore(book), 'secondary')]))); }
function download(name, content, type) { const a = el('a', { download: name, href: URL.createObjectURL(new Blob([content], { type })) }); a.click(); URL.revokeObjectURL(a.href); }
function exportJson() { download('laeseraket-backup.json', JSON.stringify(state, null, 2), 'application/json'); }
function exportCsv() { const quote = value => `"${String(value).replaceAll('"','""')}"`; download('laeseraket.csv', ['Titel,Forfatter,Sider,Læser,Dato,Reaktion,Kommentar', ...books().map(b => [b.title,b.author,b.pages,b.reader,b.date,b.emoji,b.comment].map(quote).join(','))].join('\n'), 'text/csv'); }
async function importJson(event) { try { const candidate = JSON.parse(await event.target.files[0].text()); const all = Array.isArray(candidate.books) ? candidate.books : []; const candidates = all.filter(validBook); if (!confirm(`Importen indeholder ${all.length} bogposter, hvoraf ${candidates.length} er gyldige. Sammenflet efter ID?`)) return; for (const book of candidates) save(operation(book), 'Importerer…'); announce('Importen er valideret og gennemført.'); } catch { announce('Importen kunne ikke læses eller valideres.'); } }

document.querySelectorAll('[data-close]').forEach(b => b.addEventListener('click', () => { b.closest('dialog').close(); lastFocus?.focus(); })); document.querySelectorAll('dialog').forEach(d => d.addEventListener('cancel', () => lastFocus?.focus()));
READERS.forEach(r => $('#book-form').elements.reader.append(new Option(r.name, r.id))); document.querySelectorAll('.tab').forEach(tab => tab.addEventListener('click', () => { document.querySelectorAll('.tab').forEach(t => { const active = t === tab; t.classList.toggle('active', active); t.setAttribute('aria-selected', active); $(`#${t.dataset.view}`).hidden = !active; }); }));
$('#mute').addEventListener('click', () => { state.muted = !state.muted; saveLocal(state); render(); }); addEventListener('online', sync); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js'); render(); sync();
