const GOAL=20000,PERSON_GOAL=5000,KEY='familielaeseraket-2026';
const READERS=[['marie','Marie','#FF7AC3'],['jacob','Jacob','#6FB4FF'],['alfred','Alfred','#FFC94D'],['hugo','Hugo','#5CE08A']];
const EMOJIS=['🤩','😍','😂','😭','😱','🥱'];
const EMPTY={books:[],prize:'',celebrated:[],muted:false};
let data=loadLocal(),view='home',form={t:'',a:'',p:'',r:'',e:'🤩',c:'',d:today()},displayTotal=0,flyer='',saveTimer;
const $=s=>document.querySelector(s),fmt=n=>Math.round(n).toLocaleString('da-DK'),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function today(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function clean(x){return x&&typeof x==='object'?{books:Array.isArray(x.books)?x.books:[],prize:typeof x.prize==='string'?x.prize:'',celebrated:Array.isArray(x.celebrated)?x.celebrated:[],muted:!!x.muted}:{...EMPTY}}
function loadLocal(){try{return clean(JSON.parse(localStorage.getItem(KEY)))}catch{return {...EMPTY}}}
function total(){return data.books.reduce((n,b)=>n+Number(b.p||0),0)}
function reader(key){return READERS.find(r=>r[0]===key)||['','?','#fff']}
function rocketSVG(){return `<svg viewBox="0 0 110 76" aria-label="Raket"><defs><linearGradient id="hull" x2="0" y2="1"><stop stop-color="#fff"/><stop offset=".55" stop-color="#EAF0FF"/><stop offset="1" stop-color="#C2CDEE"/></linearGradient><linearGradient id="nose" x2="0" y2="1"><stop stop-color="#FF8E53"/><stop offset="1" stop-color="#E8531C"/></linearGradient></defs><g class="flame"><path d="M17 30C6 25-7 29-16 38C-7 47 6 51 17 46C14 44 13 41 13 38C13 35 14 32 17 30Z" fill="#FFC94D"/><path d="M16 33C9 31 1 33-5 38C1 43 9 45 16 43C14 41 14 40 14 38C14 36 15 35 16 33Z" fill="#FF6B35"/></g><path d="M36 21C31 11 23 5 12 4C17 12 19 18 19 25L36 27Z" fill="url(#nose)"/><path d="M36 55C31 65 23 71 12 72C17 64 19 58 19 51L36 49Z" fill="url(#nose)"/><path d="M25 29L17 31V45L25 47Z" fill="#8E9BC4"/><path d="M31 17C27 17 24 22 24 29V47C24 54 27 59 31 59H46C66 59 85 50 97 38C85 26 66 17 46 17Z" fill="url(#hull)"/><path d="M64 19.5C78 23 90 30 97 38C90 46 78 53 64 56.5C70 50 72 44.5 72 38S70 26 64 19.5Z" fill="url(#nose)"/><circle cx="47" cy="38" r="10" fill="#8E9BC4"/><circle cx="47" cy="38" r="7.5" fill="#5FA8E8"/><circle cx="44.5" cy="35.5" r="2.6" fill="#D8ECFF"/><rect x="30" y="20.5" width="4.5" height="35" rx="2" fill="#FF6B35"/></svg>`}
function animate(from,to){const start=performance.now();function tick(now){const k=Math.min((now-start)/1300,1);displayTotal=Math.round(from+(to-from)*(1-(1-k)**3));renderHero();if(k<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
function heroHTML(){const n=total(),pct=Math.min(n/GOAL,1),start=new Date('2026-08-01T00:00:00'),end=new Date('2027-08-01T00:00:00'),now=new Date(),day=Math.max(1,Math.min(365,Math.floor((now-start)/864e5)+1)),expected=GOAL*Math.min(Math.max((now-start)/(end-start),0),1),diff=Math.round(n-expected),left=Math.max(1,Math.round((end-now)/864e5)),daily=Math.max(0,Math.ceil((GOAL-n)/left));return `<div class="hero"><div class="total">${fmt(displayTotal)}</div><div class="sub">af 20.000 sider · ${(pct*100).toLocaleString('da-DK',{maximumFractionDigits:1})} % af målet</div><div class="chips"><span class="chip ${diff>=0?'good':'behind'}">${fmt(Math.abs(diff))} sider ${diff>=0?'foran':'efter'} planen</span><span class="chip">Dag ${day} af 365</span><span class="chip">≈ ${daily} sider om dagen herfra</span></div>${data.books.length?'':'<div class="empty-note">Endnu ingen bøger i loggen — tast den første og send raketten afsted.</div>'}</div>`}
function renderHero(){const home=$('#home');if(!home)return;const old=home.querySelector('.hero');if(old)old.outerHTML=heroHTML();const n=total(),p=Math.min(n/GOAL,1),pos=`calc(70px + (100% - 156px) * ${p})`;const fill=home.querySelector('.fill'),rocket=home.querySelector('.rocket');if(fill)fill.style.width=`calc((100% - 156px) * ${p})`;if(rocket)rocket.style.left=pos}
function peopleHTML(){return READERS.map(r=>{const books=data.books.filter(b=>b.r===r[0]),pages=books.reduce((n,b)=>n+b.p,0),badges=[['🚀','Første bog',books.length>=1],['📚','5 bøger',books.length>=5],['🌙','1.000 sider',pages>=1000],['⭐','2.500 sider',pages>=2500],['🐘','En bog på 300+ sider',books.some(b=>b.p>=300)],['🏆','Personligt mål nået',pages>=PERSON_GOAL]];return `<article class="card person"><div class="identity"><div class="avatar" style="background:${r[2]}">${r[1][0]}</div><div><div class="name">${r[1]}</div><div class="meta">${books.length} ${books.length===1?'bog':'bøger'}</div></div></div><div class="pages">${fmt(pages)} <span>/ 5.000 sider</span></div><div class="bar"><i style="width:${Math.min(100,pages/PERSON_GOAL*100)}%;background:${r[2]};box-shadow:0 0 10px ${r[2]}66"></i></div><div class="badges">${badges.map(b=>`<span class="badge ${b[2]?'':'locked'}" title="${b[1]}">${b[0]}</span>`).join('')}</div></article>`}).join('')}
function formHTML(){return `<article class="card"><h2>Ny bog læst?</h2><p class="hint">Siderne skubber raketten mod præmien.</p><div class="label">HVEM HAR LÆST DEN?</div><div class="readers">${READERS.map(r=>`<button class="reader" data-reader="${r[0]}" style="${form.r===r[0]?`background:${r[2]};color:#0B1026;border-color:${r[2]}`:''}"><i style="background:${form.r===r[0]?'#0B1026':r[2]}"></i>${r[1]}</button>`).join('')}</div><form id="book-form"><div class="form-grid"><div class="full"><label>Titel</label><input name="t" required value="${esc(form.t)}" placeholder="Fx Mumitroldene og den store oversvømmelse"></div><div><label>Forfatter <small>(valgfri)</small></label><input name="a" value="${esc(form.a)}" placeholder="Tove Jansson"></div><div><label>Sidetal</label><input name="p" type="number" min="1" required value="${esc(form.p)}" placeholder="180"></div><div><label>Færdig den</label><input name="d" type="date" value="${form.d}"></div><div class="full"><label>Hvad synes du?</label><div class="reactions">${EMOJIS.map(e=>`<button type="button" class="reaction ${form.e===e?'active':''}" data-emoji="${e}">${e}</button>`).join('')}</div></div><div class="full"><label>Kommentar <small>(valgfri)</small></label><input name="c" value="${esc(form.c)}" placeholder="Den bedste bog i år!"></div></div><button class="submit" ${form.t&&form.r&&Number(form.p)>0?'':'disabled'}>Send siderne afsted</button></form></article>`}
function logHTML(){const books=[...data.books].sort((a,b)=>(b.d||'').localeCompare(a.d||'')||b.id-a.id);return `<article class="card"><div class="log-head"><h2>Logbog</h2><span class="meta">${books.length} ${books.length===1?'bog':'bøger'} · ${fmt(total())} sider</span></div>${books.length?'':`<p class="hint">Her lander bøgerne, når I taster dem ind. Den første venter på jer.</p>`}<div class="log">${books.map(b=>{const r=reader(b.r),date=new Date(`${b.d}T00:00`).toLocaleDateString('da-DK',{day:'numeric',month:'short'});return `<div class="book"><div style="font-size:24px">${b.e}</div><div class="book-main"><div class="book-title">${esc(b.t)} <span class="byline">${b.a?'· '+esc(b.a):''}</span></div><div><span class="reader-chip" style="background:${r[2]}22;color:${r[2]}">${r[1]}</span><span class="date">${date}</span></div>${b.c?`<div class="comment">“${esc(b.c)}”</div>`:''}</div><div class="book-side">+${fmt(b.p)}<button class="delete" data-delete="${b.id}" title="Slet">✕</button></div></div>`}).join('')}</div></article>`}
function renderHome(){const n=total(),p=Math.min(n/GOAL,1),pos=`calc(70px + (100% - 156px) * ${p})`;$('#home').innerHTML=heroHTML()+`<div class="track"><div class="dash"></div><div class="fill" style="width:calc((100% - 156px) * ${p})"></div><div class="start"><i></i>Start<br>1. aug 2026</div>${[25,50,75].map(m=>`<div class="mark ${p*100>=m?'done':''}" style="left:calc(70px + (100% - 156px) * ${m/100})"><i></i>${fmt(GOAL*m/100)}<small>${m} %</small></div>`).join('')}<div class="planet-wrap"><div class="planet"><i class="flag"></i></div><div class="prize-label">PRÆMIEN</div><button class="prize">${esc(data.prize||'Vælg præmien')}</button></div><div class="rocket" style="left:${pos}">${flyer?`<div class="flyer">${flyer}</div>`:''}${rocketSVG()}</div></div><div class="remaining">${n<GOAL?fmt(GOAL-n)+' sider tilbage til præmien':'Målet er nået — præmien er jeres!'}</div><div class="people">${peopleHTML()}</div><div class="bottom">${formHTML()}${logHTML()}</div>`;bindHome()}
function renderStats(){const totals=READERS.map(r=>[r,data.books.filter(b=>b.r===r[0]).reduce((n,b)=>n+b.p,0)]),max=Math.max(1,...totals.map(x=>x[1])),big=[...data.books].sort((a,b)=>b.p-a.p)[0],top=[...totals].sort((a,b)=>b[1]-a[1])[0],months=['Aug','Sep','Okt','Nov','Dec','Jan','Feb','Mar','Apr','Maj','Jun','Jul'].map((l,i)=>{const y=i<5?2026:2027,m=String((7+i)%12+1).padStart(2,'0');return[l,data.books.filter(b=>(b.d||'').startsWith(`${y}-${m}`)).reduce((n,b)=>n+b.p,0)]}),maxM=Math.max(1,...months.map(x=>x[1]));$('#stats').innerHTML=`<div class="stats-grid"><article class="card"><h2>Sider pr. person</h2>${totals.map(x=>`<div class="stat-row"><b>${x[0][1]}</b><div class="bar"><i style="width:${x[1]/max*100}%;background:${x[0][2]}"></i></div><output>${fmt(x[1])}</output></div>`).join('')}</article><article class="card"><h2>Nøgletal</h2>${[['Bøger i alt',data.books.length],['Sider i alt',fmt(total())],['Snit pr. bog',data.books.length?fmt(total()/data.books.length)+' sider':'—'],['Tykkeste bog',big?`${esc(big.t)} · ${fmt(big.p)} sider`:'—'],['Flittigste læser',top[1]?`${top[0][1]} · ${fmt(top[1])} sider`:'—']].map(f=>`<div class="fact"><span>${f[0]}</span><b>${f[1]}</b></div>`).join('')}</article><article class="card wide"><h2>Sider pr. måned</h2><div class="months">${months.map(m=>`<div class="month"><output>${m[1]?fmt(m[1]):''}</output><i style="height:${m[1]?Math.max(8,m[1]/maxM*130):3}px;${m[1]?'':'background:rgba(255,255,255,.08)'}"></i><span>${m[0]}</span></div>`).join('')}</div></article></div>`}
function bindHome(){$$('.reader').forEach(b=>b.onclick=()=>{captureForm();form.r=b.dataset.reader;renderHome()});$$('.reaction').forEach(b=>b.onclick=()=>{captureForm();form.e=b.dataset.emoji;renderHome()});$('#book-form').oninput=()=>{captureForm();const s=$('.submit');s.disabled=!(form.t.trim()&&form.r&&Number(form.p)>0)};$('#book-form').onsubmit=e=>{e.preventDefault();captureForm();addBook()};$$('.delete').forEach(b=>b.onclick=()=>deleteBook(Number(b.dataset.delete)));$('.prize').onclick=editPrize}
function $$(s){return [...document.querySelectorAll(s)]}function captureForm(){const f=$('#book-form');if(!f)return;const fd=new FormData(f);for(const k of ['t','a','p','c','d'])form[k]=String(fd.get(k)||'')}
function persist(){localStorage.setItem(KEY,JSON.stringify(data));clearTimeout(saveTimer);$('#sync').textContent='Gemmer…';saveTimer=setTimeout(syncPut,350)}
async function syncGet(){try{const res=await fetch('/api/state',{cache:'no-store'});if(!res.ok)throw Error();const remote=clean(await res.json());if(remote.books.length||remote.prize||remote.celebrated.length){data=remote;localStorage.setItem(KEY,JSON.stringify(data));render()}else if(data.books.length||data.prize){await syncPut();return}setSync('Fælles logbog er synkroniseret','ok')}catch{setSync('Offline: ændringer gemmes på denne enhed og synkroniseres senere','offline');$('#storage-copy').textContent='Data gemmes lokalt, mens fælles lager er utilgængeligt'}}
async function syncPut(){try{const res=await fetch('/api/state',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(!res.ok)throw Error();setSync('Gemt i familiens fælles logbog','ok')}catch{setSync('Gemt lokalt – kunne ikke nå fælles lager','offline')}}function setSync(s,c){$('#sync').textContent=s;$('#sync').className=`sync ${c}`}
function addBook(){const pages=parseInt(form.p,10);if(!form.t.trim()||!form.r||pages<1)return;const before=total(),book={id:Date.now(),t:form.t.trim(),a:form.a.trim(),p:pages,r:form.r,e:form.e,c:form.c.trim(),d:form.d||today()};data.books.push(book);const after=before+pages;let hit=0;for(const m of [25,50,75,100])if(before/GOAL*100<m&&after/GOAL*100>=m&&!data.celebrated.includes(m)){data.celebrated.push(m);hit=m}form={t:'',a:'',p:'',r:form.r,e:'🤩',c:'',d:today()};flyer=`+${fmt(pages)} sider`;persist();renderHome();displayTotal=before;animate(before,after);soundWhoosh();setTimeout(()=>burst(hit?220:60),900);setTimeout(()=>{flyer='';renderHome()},1800);if(hit){setTimeout(()=>fanfare(hit===100),900);if(hit===100)setTimeout(()=>{$('#overlay').hidden=false;$('#overlay-prize').textContent=data.prize||'Vælg præmien';burst(320)},900)}}
function deleteBook(id){const b=data.books.find(x=>x.id===id);if(!confirm(`Slet "${b?.t||''}"?`))return;const before=total();data.books=data.books.filter(x=>x.id!==id);persist();render();animate(before,total())}
function editPrize(){const value=prompt('Hvad er familiens præmie?',data.prize||'');if(value===null)return;data.prize=value.trim();persist();renderHome()}
function audio(){return window._lrAudio||(window._lrAudio=new AudioContext())}function tone(f,t=.0){if(data.muted)return;try{const a=audio(),o=a.createOscillator(),g=a.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.0001,a.currentTime+t);g.gain.exponentialRampToValueAtTime(.14,a.currentTime+t+.02);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+t+.35);o.connect(g).connect(a.destination);o.start(a.currentTime+t);o.stop(a.currentTime+t+.4)}catch{}}
function soundWhoosh(){tone(330)}function fanfare(big){[523,659,784,1047,...(big?[1319]:[])].forEach((f,i)=>tone(f,i*.12))}
const canvas=$('#confetti'),ctx=canvas.getContext('2d');let particles=[];function sizeCanvas(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio}function burst(n){const colors=['#FF6B35','#FFC94D','#FF7AC3','#6FB4FF','#5CE08A','#fff'];for(let i=0;i<n;i++)particles.push({x:canvas.width*.5,y:canvas.height*.3,vx:(Math.random()-.5)*16,vy:Math.random()*-10-4,l:1,c:colors[i%6],s:Math.random()*7+4});if(particles.length===n)confettiLoop()}function confettiLoop(){ctx.clearRect(0,0,canvas.width,canvas.height);particles=particles.filter(p=>p.l>0);for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.22*devicePixelRatio;p.l-=.012;ctx.globalAlpha=p.l;ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.s,p.s*.6)}ctx.globalAlpha=1;if(particles.length)requestAnimationFrame(confettiLoop)}
function render(){renderHome();renderStats();$('#mute').textContent=data.muted?'🔇':'🔊'}
for(let i=0;i<110;i++){const s=document.createElement('i');s.className='star';s.style.cssText=`left:${Math.random()*100}%;top:${Math.random()*100}%;width:${Math.random()*2.2+1}px;height:${Math.random()*2.2+1}px;--duration:${Math.random()*3+2}s;--delay:${-Math.random()*5}s`;$('#stars').append(s)}
$$('.tab').forEach(b=>b.onclick=()=>{view=b.dataset.view;$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#home').hidden=view!=='home';$('#stats').hidden=view!=='stats';if(view==='stats')renderStats()});$('#mute').onclick=()=>{data.muted=!data.muted;persist();$('#mute').textContent=data.muted?'🔇':'🔊'};$('#overlay').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.hidden=true};$('#celebrate').onclick=()=>$('#overlay').hidden=true;addEventListener('resize',sizeCanvas);sizeCanvas();displayTotal=0;render();animate(0,total());syncGet();
